### ISSUE TITLE
No javascript text is not wrapped in <noscript>

### ISSUE THREAD

**Issue by amit-feldman** [logue/vite-vue2-vuetify-ts-starter#6]
@logue you should consider wrapping the text `We're sorry but this site doesn't work properly without JavaScript enabled. Please enable it to continue.` in the index.html file in a `<noscript></noscript>` tag instead of the `<div id="app"></div>`

**Comment by logue** [comment]
This is the default text generated by Vue-CLI.

I heard that the `noscript` tag is deprecated...
https://www.w3.org/html/wg/tracker/issues/117

**Comment by amit-feldman** [comment]
@logue yeah there are a bunch of options instead of using the noscript tag, however the text is displayed everytime before the app loads and look ugly 😄. Just a suggestion though

**Comment by logue** [comment]
Well, it feels like putting a witty message or image on your own. Anyway, I think that the contents of the `title` tag should be rewritten.🙂
